version: '3.9'

services:
  api:
    container_name: evoapi
    image: atendai/evolution-api:homolog
    restart: always
    depends_on:
      - redis
      - postgres
    ports:
      - 8080:8080
    volumes:
      - evoapi_instances:/evolution/instances
    networks:
      - evoapi-net
    env_file:
      - .env

  redis:
    container_name: evoapi_redis
    image: redis:latest
    networks:
      - evoapi-net
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - evoapi_redis:/data
    ports:
      - 6379:6379
    restart: always

  postgres:
    container_name: evoapi_postgres
    image: postgres:15
    networks:
      - evoapi-net
    command: ["postgres", "-c", "max_connections=1000"]
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=evoapi_user
      - POSTGRES_PASSWORD=sua_senha_segura
      - POSTGRES_DB=evoapi_db
    volumes:
      - evoapi_postgres:/var/lib/postgresql/data

volumes:
  evoapi_instances:
  evoapi_redis:
  evoapi_postgres:

networks:
  evoapi-net:
    name: evoapi-net
    driver: bridge
